# Generated by Django 4.0.3 on 2023-05-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_graduate_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='graduate_year',
            field=models.CharField(blank=True, choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027')], max_length=255),
        ),
    ]
