# Generated by Django 2.1.5 on 2019-04-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190425_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='video',
            field=models.FileField(blank=True, upload_to='msn/video/'),
        ),
    ]
