# Generated by Django 2.1.5 on 2019-04-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190428_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Mentee', 'Mentee'), ('Mentor', 'Mentor')], max_length=255),
        ),
    ]
