# Generated by Django 2.1.5 on 2019-05-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_wechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='matched',
            field=models.BooleanField(default=False),
        ),
    ]
