# Generated by Django 2.1.5 on 2019-07-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190522_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='graduate_year',
            field=models.CharField(blank=True, choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=255),
        ),
    ]
