# Generated by Django 2.1.5 on 2019-07-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_graduate_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='credential',
            field=models.TextField(blank=True),
        ),
    ]
