# Generated by Django 2.1.5 on 2019-07-27 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190726_2214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanProfile',
        ),
    ]
