# Generated by Django 2.1.5 on 2020-05-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200419_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rm_bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='rm_schedule',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
