# Generated by Django 2.1.5 on 2020-05-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200507_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rm',
            field=models.BooleanField(default=False),
        ),
    ]
