# Generated by Django 3.1.3 on 2021-01-04 01:16

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profile_rm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanProfileVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='matchrequest',
            name='friend_request',
        ),
        migrations.RemoveField(
            model_name='planprofile',
            name='content',
        ),
        migrations.AddField(
            model_name='planprofile',
            name='latest',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='graduate_year',
            field=models.CharField(blank=True, choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=255),
        ),
        migrations.DeleteModel(
            name='MatchingHistory',
        ),
        migrations.DeleteModel(
            name='MatchRequest',
        ),
        migrations.AddField(
            model_name='planprofileversion',
            name='plan_profile',
            field=models.ForeignKey(default=users.models.get_plan_profile, on_delete=django.db.models.deletion.CASCADE, to='users.planprofile'),
        ),
    ]
