# Generated by Django 3.1.3 on 2021-01-04 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210103_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticator',
            fields=[
                ('credential', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='credential',
        ),
    ]
