# Generated by Django 3.1.3 on 2021-01-04 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210103_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='planprofileversion',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
