# Generated by Django 3.1.3 on 2021-01-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_planprofileversion_user_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticator',
            old_name='credential',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='authenticator',
            name='auth_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='authenticator',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
