# Generated by Django 2.1.5 on 2020-04-12 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('price', models.DecimalField(decimal_places=2, default='0.0', max_digits=8)),
                ('conditions', models.CharField(choices=[('New', 'New'), ('Slightly Used', 'Slightly Used'), ('Used', 'Used'), ('Dysfunctional', 'Dysfunctional')], default='Used', max_length=200)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('textbooks', 'Textbooks'), ('school supplies', 'School Supplies'), ('pets', 'Pets'), ('clothing', 'Clothing'), ('housing', 'Housing'), ('miscellaneous', 'Miscellaneous')], default='miscellaneous', max_length=25)),
                ('pickup', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='msn/market/image/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
