# Generated by Django 2.1.5 on 2020-04-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200412_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Textbooks', 'Textbooks'), ('School supplies', 'School Supplies'), ('Pets', 'Pets'), ('Clothing', 'Clothing'), ('Housing', 'Housing'), ('Miscellaneous', 'Miscellaneous')], default='miscellaneous', max_length=25),
        ),
    ]
