# Generated by Django 2.1.5 on 2020-04-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20200412_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('textbooks', 'Textbooks'), ('schoolsupplies', 'School Supplies'), ('pets', 'Pets'), ('clothing', 'Clothing'), ('housing', 'Housing'), ('miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('slightlyused', 'Slightly Used'), ('used', 'Used'), ('dysfunctional', 'Dysfunctional')], default='Used', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=10),
        ),
    ]
