# Generated by Django 2.1.5 on 2020-04-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20200415_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('textbooks', 'Textbooks'), ('schoolsupplies', 'School Supplies'), ('pets', 'Pets'), ('clothing', 'Clothing'), ('housing', 'Housing'), ('miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=25),
        ),
    ]
