# Generated by Django 2.1.5 on 2019-07-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190707_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.IntegerField(blank=True),
        ),
    ]
