# Generated by Django 2.1.5 on 2019-07-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_prerequisite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
