# Generated by Django 2.1.5 on 2019-07-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20190713_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
