# Generated by Django 2.1.5 on 2019-07-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='name',
        ),
        migrations.AddField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(default='Null', max_length=255),
        ),
        migrations.AddField(
            model_name='instructor',
            name='last_name',
            field=models.CharField(default='Null', max_length=255),
        ),
    ]
