# Generated by Django 2.1.5 on 2019-07-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20190717_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='course',
        ),
        migrations.RemoveField(
            model_name='review',
            name='course_instructor',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='topic',
        ),
        migrations.AddField(
            model_name='courseinstructor',
            name='topic',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='courseuser',
            name='course_instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseInstructor'),
        ),
        migrations.AddField(
            model_name='courseuser',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseuser',
            name='text',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
