# Generated by Django 2.1.5 on 2019-07-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20190722_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseuser',
            old_name='rating_professor',
            new_name='rating_instructor',
        ),
    ]
