# Generated by Django 2.1.5 on 2019-07-23 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20190722_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseuser',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Instructor'),
        ),
    ]
