# Generated by Django 2.1.5 on 2019-07-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_courseuser_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
