# Generated by Django 2.1.5 on 2019-07-23 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('school', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
    ]
