# Generated by Django 2.1.5 on 2019-07-23 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20190723_0847'),
    ]

    operations = [
    ]
