# Generated by Django 2.1.5 on 2019-07-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20190723_0848'),
    ]

    operations = [
    ]
