# Generated by Django 2.1.5 on 2019-07-23 13:42

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20190723_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=courses.models.get_department, on_delete=django.db.models.deletion.CASCADE, to='courses.Department'),
        ),
    ]
