# Generated by Django 2.1.5 on 2019-07-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_course_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
    ]
