# Generated by Django 2.1.5 on 2019-08-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_courseuser_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_taught',
            field=models.CharField(default='', max_length=100),
        ),
    ]
