# Generated by Django 2.1.5 on 2020-04-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_course_last_taught'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='last_taught',
            field=models.CharField(default='', max_length=100),
        ),
    ]
