# Generated by Django 3.1.3 on 2020-11-26 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_bug'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseuser',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
