# Generated by Django 3.1.3 on 2020-11-26 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_courseuser_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseuser',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
