# Generated by Django 2.1.5 on 2019-05-20 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0002_auto_20190422_1346'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_intro', models.CharField(blank=True, max_length=255)),
                ('group_name', models.CharField(blank=True, max_length=30)),
                ('group_type', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='GroupRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_role', models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Member', 'Member')], max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TagRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='group_tags',
            field=models.ManyToManyField(through='groups.TagRelation', to='skills.Skill'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_users',
            field=models.ManyToManyField(through='groups.GroupRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
