# Generated by Django 2.1.5 on 2019-05-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='msn/image/group_pics/avatar/'),
        ),
        migrations.AddField(
            model_name='group',
            name='picture',
            field=models.ImageField(blank=True, upload_to='msn/image/group_pics'),
        ),
    ]
