# Generated by Django 2.1.5 on 2019-05-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20190520_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_intro',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(blank=True, choices=[('Books', 'Books'), ('Film and TV', 'Film and TV'), ('General', 'General'), ('Game', 'Game'), ('Language', 'Language'), ('Academic Interests', 'Academic Interests'), ('Music', 'Music'), ('Sport', 'Sport'), ('Custom', 'Custom')], max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='picture',
            field=models.ImageField(blank=True, upload_to='msn/image/group_pics/'),
        ),
    ]
