# Generated by Django 2.1.5 on 2019-04-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_intro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
