# Generated by Django 2.1.5 on 2020-04-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20190422_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill_intro',
            new_name='intro',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_users',
            new_name='users',
        ),
    ]
